title: Shopee Price Police
description: How we took part of the Kaggle competition and realised its not so easy to win a lot of money...
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
